<?php
require_once("XByteArray.php");
/**
	Auto generated by xproto.exe
@author
	Dany
*/

  interface _ECUSTOM_HEADER
	{
		const php_err_length="php-err-len";
	const proto_error_code="proto-erro-code";
	const content_type="Content-type: application/xproto";
	const content_length="Content-length";
	const socket_id="HTTP_SOCKET_ID";
	const proxy_id="HTTP_PROXY_ID";
	const x_proto_type="xproto";

	}
  interface _ECOMMON_SERVER_ERROR
	{
	
		const SUCCESS =0;
		const PROXY_FASTCGI_INTERAL_ERROR =1;
		const PROXY_SENDTO_FCGI_FAILED_TOO_MUCH =2;
		const PROXY_FCGI_REQUEST_TIMEOUT =3;
		const PROXY_FCGI_UNAVAILABLE =4;
		const KICKED_OUT_BY_OTHER_DUPLICATED_LOGIN =5;
		const KICKED_OUT_FOR_IDLE_TOO_LONG =6;
		const KICKED_OUT_FOR_BAD_STATE_NOT_LOGIN_YET =7;
		const KICKED_OUT_FOR_BAD_STATE_LOING_ALREADY =8;

	}
  interface _EINTERNAL_NOTIFY_BY_PROXY
	{
	
		const CLIENT_DISCONNECT =1;
		const CLIENT_NOT_EXIST_WHEN_RESPONSE =2;
		const CLIENT_WRITE_ERROR =3;
		const CLIENT_SOCKET_DEAD_ALREADY =4;
		const PROXY_SAYHELLO_FASTCGI =5;

	}
  interface _EPROXY_STATUS
	{
	
		const OFFLINE =0;
		const BUSY =1;
		const NORMAL =2;
		const IDLE =3;

	}
  interface _ECONNECTION_STAT
	{
	
		const NONE =0;
		const CONNECTED =1;
		const AUTHENTICATED =2;
		const CREATING_CHARACTER =3;
		const ENTER_WORLD =4;
		const CLOSED =5;

	}
  interface _ETIMER_OP_ERROR
	{
	
		const SUCCEED =0;
		const TOO_MANY_TIMER =1;
		const TIMER_ID_NOT_FOUND =2;

	}
  interface _ENOTIFY_SEND_RESULT_ERROR
	{
	
		const SUCCEED =0;
		const PROXY_ID_NOT_FOUND =1;
		const PROXY_SEND_FAILED =2;
		const PROXY_ADDRESS_INVALID =3;
		const PROXY_CONNECT_FAILED =4;
		const PROXY_QUEUE_TOO_MUCH =5;
		const PROXY_OFFLINE =6;
		const PROXY_NO_LONGER_EXISTS =7;

	}
  interface _EMSG_PushInterface
	{
	
		const CMSG_SendMutiplecastPacket =1;
		const CMSG_MAX =2;

	}
  interface _EMSG_PushEvent
	{
	
		const SMSG_OnMutiplecastPacketError =1;
		const SMSG_MAX =2;

	}
  interface _EMSG_LocalInterface
	{
	
		const CMSG_SendMutiplecastLocal =1;
		const CMSG_ScheduleTimer =3;
		const CMSG_CancelTimer =4;
		const CMSG_MAX =5;

	}
  interface _EMSG_LocalEvent
	{
	
		const SMSG_OnMutiplecastLocalError =1;
		const SMSG_OnScheduleTimerResult =3;
		const SMSG_OnCancelTimerResult =4;
		const SMSG_MAX =5;

	}
  interface _EMSG_ProxyServerInterface
	{
	
		const CMSG_SendInternalNotifyByProxy =12;
		const CMSG_SendPing =34;
		const CMSG_MAX =35;

	}
  interface _EMSG_ProxyServerEvent
	{
	
		const SMSG_OnServerErrorMessage =1;
		const SMSG_OnPong =46;
		const SMSG_MAX =47;

	}
