<?php
/**
	Auto generated by xproto.exe
@author
	Dany
*/
require_once("XByteArray.php");
require_once($GLOBALS['GAME_ROOT'] . "Protocol/PROXY_TARGET_LOCAL.php");


	class XPACKET_SendMutiplecastLocal
	{
		    public static  $_m_xcmd/*:int*/=_EMSG_LocalInterface::CMSG_SendMutiplecastLocal;

	    
		public $targets =array();/*PROXY_TARGET_LOCAL[]*/
		public $bIncluded/*:UCHAR*/;
		public $pPacket="";/*UCHAR[]*/
		public $bWaitDetailResult/*:UCHAR*/;
		public $bKickout/*:UCHAR*/;

	    
	    public function XPACKET_SendMutiplecastLocal()
		{
	        $this->bIncluded =0;/*UCHAR*/
        $this->bWaitDetailResult =0;/*UCHAR*/
        $this->bKickout =0;/*UCHAR*/

		}
			
		public static function _Size($targets/*:PROXY_TARGET_LOCAL[] */ ,$bIncluded/*:UCHAR*/ ,$pPacket/*:UCHAR[] */ ,$bWaitDetailResult/*:UCHAR*/ ,$bKickout/*:UCHAR*/ )
		{
			$__xv	= 0;
			$i		=0;

            $__xv +=4;//LENGHT
            $__xv +=4;//_m_xcmd
            $__xv +=4;//XByteArray::GetDynamicLengthNumBytes(targets.length);
             foreach($targets as $_elem) $__xv += $_elem->Size();
            $__xv +=1;//bIncluded
            $__xv +=4;//XByteArray::GetDynamicLengthNumBytes(pPacket.length);
            $__xv +=1*strlen($pPacket);
            $__xv +=1;//bWaitDetailResult
            $__xv +=1;//bKickout

			return $__xv;
		}
				
		public static function _ToBuffer($__dst/*XByteArray*/,$targets/*:PROXY_TARGET_LOCAL[] */ ,$bIncluded/*:UCHAR*/ ,$pPacket/*:UCHAR[] */ ,$bWaitDetailResult/*:UCHAR*/ ,$bKickout/*:UCHAR*/ )
		{
			$__xv	= 0;
			$i		=0;

			$__dst->writeInt32(XPACKET_SendMutiplecastLocal::_Size($targets/*:PROXY_TARGET_LOCAL[] */ ,$bIncluded/*:UCHAR*/ ,$pPacket/*:UCHAR[] */ ,$bWaitDetailResult/*:UCHAR*/ ,$bKickout/*:UCHAR*/ ));
			$__xv +=4;
			$__dst->writeInt32(XPACKET_SendMutiplecastLocal::$_m_xcmd);
			$__xv +=4;

            //Write codes of targets
            //
            $__num = count($targets,0);
            $__xv +=XByteArray::WriteDynamicArrayLength($__dst,$__num);
            for($i=0;$i<$__num;$i++)
            {
                 $__xv +=$targets[$i]->ToBuffer($__dst);
            }

            //Write codes of bIncluded
            //
            $__dst->writeByte($bIncluded);
            $__xv +=1;

            //Write codes of pPacket
            //
            $__num = strlen($pPacket);
            $__xv +=XByteArray::WriteDynamicArrayLength($__dst,$__num);
            $__dst->writeBinary($pPacket,$__num);
            $__xv +=$__num;
            

            //Write codes of bWaitDetailResult
            //
            $__dst->writeByte($bWaitDetailResult);
            $__xv +=1;

            //Write codes of bKickout
            //
            $__dst->writeByte($bKickout);
            $__xv +=1;

			return $__xv;
		}
		
		public static function _ClassFromParameters($targets/*:PROXY_TARGET_LOCAL[] */ ,$bIncluded/*:UCHAR*/ ,$pPacket/*:UCHAR[] */ ,$bWaitDetailResult/*:UCHAR*/ ,$bKickout/*:UCHAR*/ )
		{
			$_class = new XPACKET_SendMutiplecastLocal();

            $_class->targets=$targets;
            $_class->bIncluded=$bIncluded;
            $_class->pPacket=$pPacket;
            $_class->bWaitDetailResult=$bWaitDetailResult;
            $_class->bKickout=$bKickout;
			
			return $_class;
		}


		public function FromBuffer($__src/*:XByteArray*/)
		{
			$__xv					= 0;
			$i						=0;
			$__xvBeanSize	=0;


            //Read codes of __xvtemp1
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp1=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of __xvtemp2
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp2=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of targets
            //
            $__targets_arrlen = new XInteger();
            $__xv +=XByteArray::ReadDynamicArrayLength($__src,$__targets_arrlen);
            if($__targets_arrlen->_value<0)
            {
                return 0;
            }
            $this->targets =array();
            for($i=0;$i<$__targets_arrlen->_value;$i++)
            {
               $__xvtmp_targets = new PROXY_TARGET_LOCAL();
               {
                   $__xvBeanSize =$__xvtmp_targets->FromBuffer($__src);
                   if($__xvBeanSize<=0) return 0;
                   $__xv +=$__xvBeanSize;
                   array_push($this->targets, $__xvtmp_targets);
               } 
            }

            //Read codes of bIncluded
            //
            if($__src->getBytesAvailable()>=1)
            {
                $this->bIncluded=$__src->readByte();
                $__xv +=1;
            }
            else
            {
                return 0;
            }

            //Read codes of pPacket
            //
            $__pPacket_arrlen = new XInteger();
            $__xv +=XByteArray::ReadDynamicArrayLength($__src,$__pPacket_arrlen);
            if($__pPacket_arrlen->_value<0)
            {
                return 0;
            }
            if($__src->getBytesAvailable()>=$__pPacket_arrlen->_value)
            {
                $this->pPacket=$__src->readBinary($__pPacket_arrlen->_value);
                $__xv +=$__pPacket_arrlen->_value;
            }
            else 
            {
                return 0;
            }
            

            //Read codes of bWaitDetailResult
            //
            if($__src->getBytesAvailable()>=1)
            {
                $this->bWaitDetailResult=$__src->readByte();
                $__xv +=1;
            }
            else
            {
                return 0;
            }

            //Read codes of bKickout
            //
            if($__src->getBytesAvailable()>=1)
            {
                $this->bKickout=$__src->readByte();
                $__xv +=1;
            }
            else
            {
                return 0;
            }

			return $__xv;
		}
		
		public function ToBuffer($__dst/*XByteArray*/)
		{
			return XPACKET_SendMutiplecastLocal::_ToBuffer($__dst,$this->targets ,$this->bIncluded ,$this->pPacket ,$this->bWaitDetailResult ,$this->bKickout );
		}
		
		public function Size()
		{
			return XPACKET_SendMutiplecastLocal::_Size($this->targets ,$this->bIncluded ,$this->pPacket ,$this->bWaitDetailResult ,$this->bKickout );
		}

    public  function FromXml(/*XP_XMLNODE_PTR*/ $pNode)
    {

        $this->targets = XFROM_XML($this->targets,$pNode,"targets",5,"PROXY_TARGET_LOCAL",3);
        $this->bIncluded = XFROM_XML($this->bIncluded,$pNode,"bIncluded",0,"");
        $this->pPacket = XFROM_XML($this->pPacket,$pNode,"pPacket",4,"",0);
        $this->bWaitDetailResult = XFROM_XML($this->bWaitDetailResult,$pNode,"bWaitDetailResult",0,"");
        $this->bKickout = XFROM_XML($this->bKickout,$pNode,"bKickout",0,"");

		  	return 0;
    }
    
    public  function   ToXml(/*XSTRING_STREAM & out*/)
    {
        $__xv_out="";

        $__xv_out .= XTO_XML($this->targets,"targets",5, 3);
        $__xv_out .= XTO_XML($this->bIncluded,"bIncluded",0, 0);
        $__xv_out .= XTO_XML($this->pPacket,"pPacket",4, 0);
        $__xv_out .= XTO_XML($this->bWaitDetailResult,"bWaitDetailResult",0, 0);
        $__xv_out .= XTO_XML($this->bKickout,"bKickout",0, 0);

        return $__xv_out;
    }
    
    public   function fromAMFObject($pNode)
    {
       
        
        $this->targets = XFROM_AMFOBJECT($this->targets,$pNode,"targets",5,"PROXY_TARGET_LOCAL",3);
        $this->bIncluded = XFROM_AMFOBJECT($this->bIncluded,$pNode,"bIncluded",0,"");
        $this->pPacket = XFROM_AMFOBJECT($this->pPacket,$pNode,"pPacket",4,"",0);
        $this->bWaitDetailResult = XFROM_AMFOBJECT($this->bWaitDetailResult,$pNode,"bWaitDetailResult",0,"");
        $this->bKickout = XFROM_AMFOBJECT($this->bKickout,$pNode,"bKickout",0,"");

        return 0;
    }
		
	private static function ParamDebugString($param)
    {
    	if (is_object($param))
    	{
    		return $param->ToDebugString();
    	}
    	else if (is_array($param))
    	{
    		$str = "(";
    		foreach($param as $p)
    		{
    			if( is_object($p) )
    			{
    				$str .= $p->ToDebugString().",";
			}
			else
			{
				$str .= strval($p).",";
			}
    		}
    		$str .= ")";
    		$str = str_replace(",)",")",$str);
    		return $str;
    	}
    	
    	return strval($param);
    } 
    
	public  function ToDebugString()
    {
    	if(XPACKET_SendMutiplecastLocal::$_m_xcmd == _EMSG_ServerEvent::SMSG_OnSendZipData){
    		return "([ignore zip data])";
    	}
		
    	$__xv_out  = "(";
    	
        $__xv_out .= "targets=".$this->ParamDebugString($this->targets).",";
        $__xv_out .= "bIncluded=".$this->ParamDebugString($this->bIncluded).",";
        $__xv_out .= "pPacket=".$this->ParamDebugString($this->pPacket).",";
        $__xv_out .= "bWaitDetailResult=".$this->ParamDebugString($this->bWaitDetailResult).",";
        $__xv_out .= "bKickout=".$this->ParamDebugString($this->bKickout).",";

    	
    	$__xv_out  .= ")";
    	
    	$__xv_out = str_replace(",)",")",$__xv_out);
    	
    	return $__xv_out;
    }
    
   	public static function toAMFObject($__dst/*XByteArray*/,$targets/*:PROXY_TARGET_LOCAL[] */ ,$bIncluded/*:UCHAR*/ ,$pPacket/*:UCHAR[] */ ,$bWaitDetailResult/*:UCHAR*/ ,$bKickout/*:UCHAR*/ )
		{
			$__xv	= 0;
			$i		=0;
      $obj = array();

        $obj["targets"]=$targets ;
        $obj["bIncluded"]=$bIncluded ;
        $obj["pPacket"]=$pPacket ;
        $obj["bWaitDetailResult"]=$bWaitDetailResult ;
        $obj["bKickout"]=$bKickout ;

      if(count($obj)>0)
      {
          $outBuffer  = WriteAMF3Object($obj);
          $__xv = strlen($outBuffer);
          $__xv+=8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_SendMutiplecastLocal::$_m_xcmd);
          $__dst->writeBinary($outBuffer,strlen($outBuffer));
      }
      else
      {
          $__xv =8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_SendMutiplecastLocal::$_m_xcmd);
      }
      
      
			return $__xv;
		}
	}
	
	
?>
