<?php
/**
	Auto generated by xproto.exe
@author
	Dany
*/
require_once("XByteArray.php");
require_once($GLOBALS['GAME_ROOT'] . "Protocol/NotifySendResult.php");


	class XPACKET_OnMutiplecastLocalError
	{
		    public static  $_m_xcmd/*:int*/=_EMSG_LocalEvent::SMSG_OnMutiplecastLocalError;

	    
		public $res =array();/*NotifySendResult[]*/

	    
	    public function XPACKET_OnMutiplecastLocalError()
		{
	
		}
			
		public static function _Size($res/*:NotifySendResult[] */ )
		{
			$__xv	= 0;
			$i		=0;

            $__xv +=4;//LENGHT
            $__xv +=4;//_m_xcmd
            $__xv +=4;//XByteArray::GetDynamicLengthNumBytes(res.length);
             foreach($res as $_elem) $__xv += $_elem->Size();

			return $__xv;
		}
				
		public static function _ToBuffer($__dst/*XByteArray*/,$res/*:NotifySendResult[] */ )
		{
			$__xv	= 0;
			$i		=0;

			$__dst->writeInt32(XPACKET_OnMutiplecastLocalError::_Size($res/*:NotifySendResult[] */ ));
			$__xv +=4;
			$__dst->writeInt32(XPACKET_OnMutiplecastLocalError::$_m_xcmd);
			$__xv +=4;

            //Write codes of res
            //
            $__num = count($res,0);
            $__xv +=XByteArray::WriteDynamicArrayLength($__dst,$__num);
            for($i=0;$i<$__num;$i++)
            {
                 $__xv +=$res[$i]->ToBuffer($__dst);
            }

			return $__xv;
		}
		
		public static function _ClassFromParameters($res/*:NotifySendResult[] */ )
		{
			$_class = new XPACKET_OnMutiplecastLocalError();

            $_class->res=$res;
			
			return $_class;
		}


		public function FromBuffer($__src/*:XByteArray*/)
		{
			$__xv					= 0;
			$i						=0;
			$__xvBeanSize	=0;


            //Read codes of __xvtemp1
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp1=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of __xvtemp2
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp2=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of res
            //
            $__res_arrlen = new XInteger();
            $__xv +=XByteArray::ReadDynamicArrayLength($__src,$__res_arrlen);
            if($__res_arrlen->_value<0)
            {
                return 0;
            }
            $this->res =array();
            for($i=0;$i<$__res_arrlen->_value;$i++)
            {
               $__xvtmp_res = new NotifySendResult();
               {
                   $__xvBeanSize =$__xvtmp_res->FromBuffer($__src);
                   if($__xvBeanSize<=0) return 0;
                   $__xv +=$__xvBeanSize;
                   array_push($this->res, $__xvtmp_res);
               } 
            }

			return $__xv;
		}
		
		public function ToBuffer($__dst/*XByteArray*/)
		{
			return XPACKET_OnMutiplecastLocalError::_ToBuffer($__dst,$this->res );
		}
		
		public function Size()
		{
			return XPACKET_OnMutiplecastLocalError::_Size($this->res );
		}

    public  function FromXml(/*XP_XMLNODE_PTR*/ $pNode)
    {

        $this->res = XFROM_XML($this->res,$pNode,"res",5,"NotifySendResult",3);

		  	return 0;
    }
    
    public  function   ToXml(/*XSTRING_STREAM & out*/)
    {
        $__xv_out="";

        $__xv_out .= XTO_XML($this->res,"res",5, 3);

        return $__xv_out;
    }
    
    public   function fromAMFObject($pNode)
    {
       
        
        $this->res = XFROM_AMFOBJECT($this->res,$pNode,"res",5,"NotifySendResult",3);

        return 0;
    }
		
	private static function ParamDebugString($param)
    {
    	if (is_object($param))
    	{
    		return $param->ToDebugString();
    	}
    	else if (is_array($param))
    	{
    		$str = "(";
    		foreach($param as $p)
    		{
    			if( is_object($p) )
    			{
    				$str .= $p->ToDebugString().",";
			}
			else
			{
				$str .= strval($p).",";
			}
    		}
    		$str .= ")";
    		$str = str_replace(",)",")",$str);
    		return $str;
    	}
    	
    	return strval($param);
    } 
    
	public  function ToDebugString()
    {
    	if(XPACKET_OnMutiplecastLocalError::$_m_xcmd == _EMSG_ServerEvent::SMSG_OnSendZipData){
    		return "([ignore zip data])";
    	}
		
    	$__xv_out  = "(";
    	
        $__xv_out .= "res=".$this->ParamDebugString($this->res).",";

    	
    	$__xv_out  .= ")";
    	
    	$__xv_out = str_replace(",)",")",$__xv_out);
    	
    	return $__xv_out;
    }
    
   	public static function toAMFObject($__dst/*XByteArray*/,$res/*:NotifySendResult[] */ )
		{
			$__xv	= 0;
			$i		=0;
      $obj = array();

        $obj["res"]=$res ;

      if(count($obj)>0)
      {
          $outBuffer  = WriteAMF3Object($obj);
          $__xv = strlen($outBuffer);
          $__xv+=8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_OnMutiplecastLocalError::$_m_xcmd);
          $__dst->writeBinary($outBuffer,strlen($outBuffer));
      }
      else
      {
          $__xv =8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_OnMutiplecastLocalError::$_m_xcmd);
      }
      
      
			return $__xv;
		}
	}
	
	
?>
