<?php
/**
	Auto generated by xproto.exe
@author
	Dany
*/
require_once("XByteArray.php");


	class XPACKET_DoLogin
	{
		    public static  $_m_xcmd/*:int*/=_EMSG_ServerInterface::CMSG_DoLogin;

	    
		public $userId/*:string utf-8*/="";
		public $server/*:string utf-8*/="";
		public $sessionKey/*:string utf-8*/="";
		public $version/*:string utf-8*/="";

	    
	    public function XPACKET_DoLogin()
		{
	
		}
			
		public static function _Size($userId/*:string utf-8*/ ,$server/*:string utf-8*/ ,$sessionKey/*:string utf-8*/ ,$version/*:string utf-8*/ )
		{
			$__xv	= 0;
			$i		=0;

            $__xv +=4;//LENGHT
            $__xv +=4;//_m_xcmd
            $__xv +=XByteArray::StringASize($userId);
            $__xv +=XByteArray::StringASize($server);
            $__xv +=XByteArray::StringASize($sessionKey);
            $__xv +=XByteArray::StringASize($version);

			return $__xv;
		}
				
		public static function _ToBuffer($__dst/*XByteArray*/,$userId/*:string utf-8*/ ,$server/*:string utf-8*/ ,$sessionKey/*:string utf-8*/ ,$version/*:string utf-8*/ )
		{
			$__xv	= 0;
			$i		=0;

			$__dst->writeInt32(XPACKET_DoLogin::_Size($userId/*:string utf-8*/ ,$server/*:string utf-8*/ ,$sessionKey/*:string utf-8*/ ,$version/*:string utf-8*/ ));
			$__xv +=4;
			$__dst->writeInt32(XPACKET_DoLogin::$_m_xcmd);
			$__xv +=4;

            //Write codes of userId
            //
             $__xv += XByteArray::WriteStringA($__dst, $userId);

            //Write codes of server
            //
             $__xv += XByteArray::WriteStringA($__dst, $server);

            //Write codes of sessionKey
            //
             $__xv += XByteArray::WriteStringA($__dst, $sessionKey);

            //Write codes of version
            //
             $__xv += XByteArray::WriteStringA($__dst, $version);

			return $__xv;
		}
		
		public static function _ClassFromParameters($userId/*:string utf-8*/ ,$server/*:string utf-8*/ ,$sessionKey/*:string utf-8*/ ,$version/*:string utf-8*/ )
		{
			$_class = new XPACKET_DoLogin();

            $_class->userId=$userId;
            $_class->server=$server;
            $_class->sessionKey=$sessionKey;
            $_class->version=$version;
			
			return $_class;
		}


		public function FromBuffer($__src/*:XByteArray*/)
		{
			$__xv					= 0;
			$i						=0;
			$__xvBeanSize	=0;


            //Read codes of __xvtemp1
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp1=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of __xvtemp2
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp2=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of userId
            //
            $__userId_szSize	= new XInteger();
            $this->userId =XByteArray::ReadStringA($__src,$__userId_szSize);
            if($__userId_szSize->_value<=0) 
                return 0;
            $__xv +=$__userId_szSize->_value;

            //Read codes of server
            //
            $__server_szSize	= new XInteger();
            $this->server =XByteArray::ReadStringA($__src,$__server_szSize);
            if($__server_szSize->_value<=0) 
                return 0;
            $__xv +=$__server_szSize->_value;

            //Read codes of sessionKey
            //
            $__sessionKey_szSize	= new XInteger();
            $this->sessionKey =XByteArray::ReadStringA($__src,$__sessionKey_szSize);
            if($__sessionKey_szSize->_value<=0) 
                return 0;
            $__xv +=$__sessionKey_szSize->_value;

            //Read codes of version
            //
            $__version_szSize	= new XInteger();
            $this->version =XByteArray::ReadStringA($__src,$__version_szSize);
            if($__version_szSize->_value<=0) 
                return 0;
            $__xv +=$__version_szSize->_value;

			return $__xv;
		}
		
		public function ToBuffer($__dst/*XByteArray*/)
		{
			return XPACKET_DoLogin::_ToBuffer($__dst,$this->userId ,$this->server ,$this->sessionKey ,$this->version );
		}
		
		public function Size()
		{
			return XPACKET_DoLogin::_Size($this->userId ,$this->server ,$this->sessionKey ,$this->version );
		}

    public  function FromXml(/*XP_XMLNODE_PTR*/ $pNode)
    {

        $this->userId = XFROM_XML($this->userId,$pNode,"userId",2,"");
        $this->server = XFROM_XML($this->server,$pNode,"server",2,"");
        $this->sessionKey = XFROM_XML($this->sessionKey,$pNode,"sessionKey",2,"");
        $this->version = XFROM_XML($this->version,$pNode,"version",2,"");

		  	return 0;
    }
    
    public  function   ToXml(/*XSTRING_STREAM & out*/)
    {
        $__xv_out="";

        $__xv_out .= XTO_XML($this->userId,"userId",2, 0);
        $__xv_out .= XTO_XML($this->server,"server",2, 0);
        $__xv_out .= XTO_XML($this->sessionKey,"sessionKey",2, 0);
        $__xv_out .= XTO_XML($this->version,"version",2, 0);

        return $__xv_out;
    }
    
    public   function fromAMFObject($pNode)
    {
       
        
        $this->userId = XFROM_AMFOBJECT($this->userId,$pNode,"userId",2,"");
        $this->server = XFROM_AMFOBJECT($this->server,$pNode,"server",2,"");
        $this->sessionKey = XFROM_AMFOBJECT($this->sessionKey,$pNode,"sessionKey",2,"");
        $this->version = XFROM_AMFOBJECT($this->version,$pNode,"version",2,"");

        return 0;
    }
		
	private static function ParamDebugString($param)
    {
    	if (is_object($param))
    	{
    		return $param->ToDebugString();
    	}
    	else if (is_array($param))
    	{
    		$str = "(";
    		foreach($param as $p)
    		{
    			if( is_object($p) )
    			{
    				$str .= $p->ToDebugString().",";
			}
			else
			{
				$str .= strval($p).",";
			}
    		}
    		$str .= ")";
    		$str = str_replace(",)",")",$str);
    		return $str;
    	}
    	
    	return strval($param);
    } 
    
	public  function ToDebugString()
    {
    	if(XPACKET_DoLogin::$_m_xcmd == _EMSG_ServerEvent::SMSG_OnSendZipData){
    		return "([ignore zip data])";
    	}
		
    	$__xv_out  = "(";
    	
        $__xv_out .= "userId=".$this->ParamDebugString($this->userId).",";
        $__xv_out .= "server=".$this->ParamDebugString($this->server).",";
        $__xv_out .= "sessionKey=".$this->ParamDebugString($this->sessionKey).",";
        $__xv_out .= "version=".$this->ParamDebugString($this->version).",";

    	
    	$__xv_out  .= ")";
    	
    	$__xv_out = str_replace(",)",")",$__xv_out);
    	
    	return $__xv_out;
    }
    
   	public static function toAMFObject($__dst/*XByteArray*/,$userId/*:string utf-8*/ ,$server/*:string utf-8*/ ,$sessionKey/*:string utf-8*/ ,$version/*:string utf-8*/ )
		{
			$__xv	= 0;
			$i		=0;
      $obj = array();

        $obj["userId"]=$userId ;
        $obj["server"]=$server ;
        $obj["sessionKey"]=$sessionKey ;
        $obj["version"]=$version ;

      if(count($obj)>0)
      {
          $outBuffer  = WriteAMF3Object($obj);
          $__xv = strlen($outBuffer);
          $__xv+=8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_DoLogin::$_m_xcmd);
          $__dst->writeBinary($outBuffer,strlen($outBuffer));
      }
      else
      {
          $__xv =8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_DoLogin::$_m_xcmd);
      }
      
      
			return $__xv;
		}
	}
	
	
?>
