<?php
/**
	Auto generated by xproto.exe
@author
	Dany
*/
require_once("XByteArray.php");


	class XPACKET_OnServerErrorMessage
	{
		    public static  $_m_xcmd/*:int*/=_EMSG_ServerEvent::SMSG_OnServerErrorMessage;

	    
		public $error_code/*:INT*/;
		public $lpszMsg/*:string utf-8*/="";

	    
	    public function XPACKET_OnServerErrorMessage()
		{
	        $this->error_code =0;/*INT*/

		}
			
		public static function _Size($error_code/*:INT*/ ,$lpszMsg/*:string utf-8*/ )
		{
			$__xv	= 0;
			$i		=0;

            $__xv +=4;//LENGHT
            $__xv +=4;//_m_xcmd
            $__xv +=4;//error_code
            $__xv +=XByteArray::StringASize($lpszMsg);

			return $__xv;
		}
				
		public static function _ToBuffer($__dst/*XByteArray*/,$error_code/*:INT*/ ,$lpszMsg/*:string utf-8*/ )
		{
			$__xv	= 0;
			$i		=0;

			$__dst->writeInt32(XPACKET_OnServerErrorMessage::_Size($error_code/*:INT*/ ,$lpszMsg/*:string utf-8*/ ));
			$__xv +=4;
			$__dst->writeInt32(XPACKET_OnServerErrorMessage::$_m_xcmd);
			$__xv +=4;

            //Write codes of error_code
            //
            $__dst->writeInt32($error_code);
            $__xv +=4;

            //Write codes of lpszMsg
            //
             $__xv += XByteArray::WriteStringA($__dst, $lpszMsg);

			return $__xv;
		}
		
		public static function _ClassFromParameters($error_code/*:INT*/ ,$lpszMsg/*:string utf-8*/ )
		{
			$_class = new XPACKET_OnServerErrorMessage();

            $_class->error_code=$error_code;
            $_class->lpszMsg=$lpszMsg;
			
			return $_class;
		}


		public function FromBuffer($__src/*:XByteArray*/)
		{
			$__xv					= 0;
			$i						=0;
			$__xvBeanSize	=0;


            //Read codes of __xvtemp1
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp1=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of __xvtemp2
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp2=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of error_code
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->error_code=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of lpszMsg
            //
            $__lpszMsg_szSize	= new XInteger();
            $this->lpszMsg =XByteArray::ReadStringA($__src,$__lpszMsg_szSize);
            if($__lpszMsg_szSize->_value<=0) 
                return 0;
            $__xv +=$__lpszMsg_szSize->_value;

			return $__xv;
		}
		
		public function ToBuffer($__dst/*XByteArray*/)
		{
			return XPACKET_OnServerErrorMessage::_ToBuffer($__dst,$this->error_code ,$this->lpszMsg );
		}
		
		public function Size()
		{
			return XPACKET_OnServerErrorMessage::_Size($this->error_code ,$this->lpszMsg );
		}

    public  function FromXml(/*XP_XMLNODE_PTR*/ $pNode)
    {

        $this->error_code = XFROM_XML($this->error_code,$pNode,"error_code",0,"");
        $this->lpszMsg = XFROM_XML($this->lpszMsg,$pNode,"lpszMsg",2,"");

		  	return 0;
    }
    
    public  function   ToXml(/*XSTRING_STREAM & out*/)
    {
        $__xv_out="";

        $__xv_out .= XTO_XML($this->error_code,"error_code",0, 0);
        $__xv_out .= XTO_XML($this->lpszMsg,"lpszMsg",2, 0);

        return $__xv_out;
    }
    
    public   function fromAMFObject($pNode)
    {
       
        
        $this->error_code = XFROM_AMFOBJECT($this->error_code,$pNode,"error_code",0,"");
        $this->lpszMsg = XFROM_AMFOBJECT($this->lpszMsg,$pNode,"lpszMsg",2,"");

        return 0;
    }
		
	private static function ParamDebugString($param)
    {
    	if (is_object($param))
    	{
    		return $param->ToDebugString();
    	}
    	else if (is_array($param))
    	{
    		$str = "(";
    		foreach($param as $p)
    		{
    			if( is_object($p) )
    			{
    				$str .= $p->ToDebugString().",";
			}
			else
			{
				$str .= strval($p).",";
			}
    		}
    		$str .= ")";
    		$str = str_replace(",)",")",$str);
    		return $str;
    	}
    	
    	return strval($param);
    } 
    
	public  function ToDebugString()
    {
    	if(XPACKET_OnServerErrorMessage::$_m_xcmd == _EMSG_ServerEvent::SMSG_OnSendZipData){
    		return "([ignore zip data])";
    	}
		
    	$__xv_out  = "(";
    	
        $__xv_out .= "error_code=".$this->ParamDebugString($this->error_code).",";
        $__xv_out .= "lpszMsg=".$this->ParamDebugString($this->lpszMsg).",";

    	
    	$__xv_out  .= ")";
    	
    	$__xv_out = str_replace(",)",")",$__xv_out);
    	
    	return $__xv_out;
    }
    
   	public static function toAMFObject($__dst/*XByteArray*/,$error_code/*:INT*/ ,$lpszMsg/*:string utf-8*/ )
		{
			$__xv	= 0;
			$i		=0;
      $obj = array();

        $obj["error_code"]=$error_code ;
        $obj["lpszMsg"]=$lpszMsg ;

      if(count($obj)>0)
      {
          $outBuffer  = WriteAMF3Object($obj);
          $__xv = strlen($outBuffer);
          $__xv+=8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_OnServerErrorMessage::$_m_xcmd);
          $__dst->writeBinary($outBuffer,strlen($outBuffer));
      }
      else
      {
          $__xv =8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_OnServerErrorMessage::$_m_xcmd);
      }
      
      
			return $__xv;
		}
	}
	
	
?>
