<?php
/**
	Auto generated by xproto.exe
@author
	Dany
*/
require_once("XByteArray.php");
require_once($GLOBALS['GAME_ROOT'] . "Protocol/XLONGLONG.php");
require_once($GLOBALS['GAME_ROOT'] . "Protocol/NotifySendResult.php");


	class XPACKET_OnMutiplecastPacketError
	{
		    public static  $_m_xcmd/*:int*/=_EMSG_PushEvent::SMSG_OnMutiplecastPacketError;

	    
		public $request_id/*:XLONGLONG*/;
		public $res/*:NotifySendResult*/;

	    
	    public function XPACKET_OnMutiplecastPacketError()
		{
	        $this->request_id =new XLONGLONG();
        $this->res =new NotifySendResult();

		}
			
		public static function _Size($request_id/*:XLONGLONG*/ ,$res/*:NotifySendResult*/ )
		{
			$__xv	= 0;
			$i		=0;

            $__xv +=4;//LENGHT
            $__xv +=4;//_m_xcmd
            $__xv +=$request_id->Size();
            $__xv +=$res->Size();

			return $__xv;
		}
				
		public static function _ToBuffer($__dst/*XByteArray*/,$request_id/*:XLONGLONG*/ ,$res/*:NotifySendResult*/ )
		{
			$__xv	= 0;
			$i		=0;

			$__dst->writeInt32(XPACKET_OnMutiplecastPacketError::_Size($request_id/*:XLONGLONG*/ ,$res/*:NotifySendResult*/ ));
			$__xv +=4;
			$__dst->writeInt32(XPACKET_OnMutiplecastPacketError::$_m_xcmd);
			$__xv +=4;
            $__xv +=$request_id->ToBuffer($__dst);
            $__xv +=$res->ToBuffer($__dst);

			return $__xv;
		}
		
		public static function _ClassFromParameters($request_id/*:XLONGLONG*/ ,$res/*:NotifySendResult*/ )
		{
			$_class = new XPACKET_OnMutiplecastPacketError();

            $_class->request_id=$request_id;
            $_class->res=$res;
			
			return $_class;
		}


		public function FromBuffer($__src/*:XByteArray*/)
		{
			$__xv					= 0;
			$i						=0;
			$__xvBeanSize	=0;


            //Read codes of __xvtemp1
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp1=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of __xvtemp2
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp2=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }
            $__xv +=$this->request_id->FromBuffer($__src);
            $__xv +=$this->res->FromBuffer($__src);

			return $__xv;
		}
		
		public function ToBuffer($__dst/*XByteArray*/)
		{
			return XPACKET_OnMutiplecastPacketError::_ToBuffer($__dst,$this->request_id ,$this->res );
		}
		
		public function Size()
		{
			return XPACKET_OnMutiplecastPacketError::_Size($this->request_id ,$this->res );
		}

    public  function FromXml(/*XP_XMLNODE_PTR*/ $pNode)
    {

        $this->request_id = XFROM_XML($this->request_id,$pNode,"request_id",3,"");
        $this->res = XFROM_XML($this->res,$pNode,"res",3,"");

		  	return 0;
    }
    
    public  function   ToXml(/*XSTRING_STREAM & out*/)
    {
        $__xv_out="";

        $__xv_out .= XTO_XML($this->request_id,"request_id",3, 0);
        $__xv_out .= XTO_XML($this->res,"res",3, 0);

        return $__xv_out;
    }
    
    public   function fromAMFObject($pNode)
    {
       
        
        $this->request_id = XFROM_AMFOBJECT($this->request_id,$pNode,"request_id",3,"");
        $this->res = XFROM_AMFOBJECT($this->res,$pNode,"res",3,"");

        return 0;
    }
		
	private static function ParamDebugString($param)
    {
    	if (is_object($param))
    	{
    		return $param->ToDebugString();
    	}
    	else if (is_array($param))
    	{
    		$str = "(";
    		foreach($param as $p)
    		{
    			if( is_object($p) )
    			{
    				$str .= $p->ToDebugString().",";
			}
			else
			{
				$str .= strval($p).",";
			}
    		}
    		$str .= ")";
    		$str = str_replace(",)",")",$str);
    		return $str;
    	}
    	
    	return strval($param);
    } 
    
	public  function ToDebugString()
    {
    	if(XPACKET_OnMutiplecastPacketError::$_m_xcmd == _EMSG_ServerEvent::SMSG_OnSendZipData){
    		return "([ignore zip data])";
    	}
		
    	$__xv_out  = "(";
    	
        $__xv_out .= "request_id=".$this->ParamDebugString($this->request_id).",";
        $__xv_out .= "res=".$this->ParamDebugString($this->res).",";

    	
    	$__xv_out  .= ")";
    	
    	$__xv_out = str_replace(",)",")",$__xv_out);
    	
    	return $__xv_out;
    }
    
   	public static function toAMFObject($__dst/*XByteArray*/,$request_id/*:XLONGLONG*/ ,$res/*:NotifySendResult*/ )
		{
			$__xv	= 0;
			$i		=0;
      $obj = array();

        $obj["request_id"]=$request_id ;
        $obj["res"]=$res ;

      if(count($obj)>0)
      {
          $outBuffer  = WriteAMF3Object($obj);
          $__xv = strlen($outBuffer);
          $__xv+=8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_OnMutiplecastPacketError::$_m_xcmd);
          $__dst->writeBinary($outBuffer,strlen($outBuffer));
      }
      else
      {
          $__xv =8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_OnMutiplecastPacketError::$_m_xcmd);
      }
      
      
			return $__xv;
		}
	}
	
	
?>
