del	UI\art\card_bg_big_52*
del	UI\art\card_bg_big_53*
del	UI\art\card_bg_big_54*

del	UI\art\card_bg_big_1_s*
del	UI\art\card_bg_big_5_s*
del	UI\art\card_bg_big_8_s*
del	UI\art\card_bg_big_13_s*
del	UI\art\card_bg_big_14_s*
del	UI\art\card_bg_big_23_s*
del	UI\art\card_bg_big_24_s*
del	UI\art\card_bg_big_28_s*

del	UI\art\card_name_52_big*
del	UI\art\card_name_53_big*
del	UI\art\card_name_54_big*

del	UI\portrait\dialogue_portrait_52*
del	UI\portrait\dialogue_portrait_53*
del	UI\portrait\dialogue_portrait_54*

del UI\HERO-NAME\get_new_hero_name_52*
del UI\HERO-NAME\get_new_hero_name_53*
del UI\HERO-NAME\get_new_hero_name_54*


del	UI\HERO\*_alpha_mask
del	UI\ITEM\*_alpha_mask
del	UI\art\*_alpha_mask

del	UI\alpha\HVGA\excavate\* /q

del	anim\TitanHead.ccc
del	anim\TitanHead_down.ccc
del	anim\TitanHead_up.ccc
del	anim\Footman.ccc
del	anim\Gorilla.ccc
del	anim\Mortar.ccc
del	anim\Sheep.ccc
del	anim\Sheep2.ccc
del	anim\SliverDragon.ccc
del	anim\Sorceress.ccc
del	anim\Spider.ccc
del	anim\Archer.ccc
del	anim\effect\eff_UI_Main_Spring.ccc

del	UI\HERO\Archer*
del	UI\HERO\Kael*
del	UI\HERO\Lancer*
del	UI\HERO\Phoenix*
del	UI\HERO\SwitchAxe*
del	UI\HERO\SwitchNaga*
del	UI\HERO\SwitchOK*
del	UI\HERO\SwitchOM*
del	UI\HERO\SwitchRazor*
del	UI\HERO\SwitchSG*
del	UI\HERO\SwitchUrsa*

del	sound\*.wav
del	sound_menu\*.wav
del	sound_menu\heroes_voice\*.wav

del	sound_menu\heroes_voice\voice_TB_*
del	sound_menu\heroes_voice\voice_AM_*
del	sound_menu\heroes_voice\voice_Footman_*


del	UI\ITEM\441.*
del	UI\ITEM\468.*
del	UI\ITEM\469.*
del	UI\ITEM\s135.*
del	UI\ITEM\s145.*
del	UI\ITEM\s15.*
del	UI\ITEM\s236.*
del	UI\ITEM\s245.*
del	UI\ITEM\s285.*
del	UI\ITEM\s520.*
del	UI\ITEM\s522.*
del	UI\ITEM\s523.*
del	UI\ITEM\s524.*
del	UI\ITEM\s5300.*
del	UI\ITEM\s5302.*
del	UI\ITEM\s5303.*
del	UI\ITEM\s5304.*
del	UI\ITEM\s531.*
del	UI\ITEM\s533.*
del	UI\ITEM\s534.*
del	UI\ITEM\s535.*
del	UI\ITEM\s536.*
del	UI\ITEM\s537.*
del	UI\ITEM\s538.*
del	UI\ITEM\s539.*
del	UI\ITEM\s540.*
del	UI\ITEM\s542.*
del	UI\ITEM\s543.*
del	UI\ITEM\s544.*
del	UI\ITEM\s55.*
del	UI\ITEM\s85.*
del	UI\ITEM\z1.*
del	UI\ITEM\z13.*
del	UI\ITEM\z13_s.*
del	UI\ITEM\z14.*
del	UI\ITEM\z14_s.*
del	UI\ITEM\z1_s.*
del	UI\ITEM\z23.*
del	UI\ITEM\z23_s.*
del	UI\ITEM\z24.*
del	UI\ITEM\z24_s.*
del	UI\ITEM\z28.*
del	UI\ITEM\z28_s.*
del	UI\ITEM\z5.*
del	UI\ITEM\z5_s.*
del	UI\ITEM\z8.*
del	UI\ITEM\z8_s.*
del	UI\ITEM\z_blue.*
del	UI\ITEM\z_bule.*
del	UI\ITEM\z_gold.*
del	UI\ITEM\z_green.*
del	UI\ITEM\z_purple.*
del	UI\ITEM\z_red.*

del	UI\ITEM\441_alpha*
del	UI\ITEM\468_alpha*
del	UI\ITEM\469_alpha*
del	UI\ITEM\s135_alpha*
del	UI\ITEM\s145_alpha*
del	UI\ITEM\s15_alpha*
del	UI\ITEM\s236_alpha*
del	UI\ITEM\s245_alpha*
del	UI\ITEM\s285_alpha*
del	UI\ITEM\s520_alpha*
del	UI\ITEM\s522_alpha*
del	UI\ITEM\s523_alpha*
del	UI\ITEM\s524_alpha*
del	UI\ITEM\s5300_alpha*
del	UI\ITEM\s5302_alpha*
del	UI\ITEM\s5303_alpha*
del	UI\ITEM\s5304_alpha*
del	UI\ITEM\s531_alpha*
del	UI\ITEM\s533_alpha*
del	UI\ITEM\s534_alpha*
del	UI\ITEM\s535_alpha*
del	UI\ITEM\s536_alpha*
del	UI\ITEM\s537_alpha*
del	UI\ITEM\s538_alpha*
del	UI\ITEM\s539_alpha*
del	UI\ITEM\s540_alpha*
del	UI\ITEM\s542_alpha*
del	UI\ITEM\s543_alpha*
del	UI\ITEM\s544_alpha*
del	UI\ITEM\s55_alpha*
del	UI\ITEM\s85_alpha*
del	UI\ITEM\z1_alpha*
del	UI\ITEM\z13_alpha*
del	UI\ITEM\z13_s_alpha*
del	UI\ITEM\z14_alpha*
del	UI\ITEM\z14_s_alpha*
del	UI\ITEM\z1_s_alpha*
del	UI\ITEM\z23_alpha*
del	UI\ITEM\z23_s_alpha*
del	UI\ITEM\z24_alpha*
del	UI\ITEM\z24_s_alpha*
del	UI\ITEM\z28_alpha*
del	UI\ITEM\z28_s_alpha*
del	UI\ITEM\z5_alpha*
del	UI\ITEM\z5_s_alpha*
del	UI\ITEM\z8_alpha*
del	UI\ITEM\z8_s_alpha*
del	UI\ITEM\z_blue_alpha*
del	UI\ITEM\z_bule_alpha*
del	UI\ITEM\z_gold_alpha*
del	UI\ITEM\z_green_alpha*
del	UI\ITEM\z_purple_alpha*
del	UI\ITEM\z_red_alpha*