<?php
/**
	Auto generated by xproto.exe
@author
	Dany
*/
require_once("XByteArray.php");
/*::PARENT_CLASS_NAME_INCLUDE::*/
/*::MEMBER_CLASS_NAME_INCLUDE::*/

	class /*::BEAN_CLASS_NAME::*/ /*::PARENT_CLASS_NAME::*/
	{
		/*{::PACKET_COMMAND_DEFINES::}*/
	    /*{::CLASS_MEMBER_DEFINES::}*/
	    
		public function /*::BEAN_CLASS_NAME::*/()
		{
/**::SMART_POINTER_CONSTRUCT::**/
		}
		
		public /*::OVER_RIDE::*/ function FromBuffer($__src/*:XByteArray*/)
		{
			$__xv  = 0;
			$i		 = 0;
			$__xvBeanSize=0;
/*{::FROM_BUFFER_CODES::}*/
			return $__xv;
		}
		
		public /*::OVER_RIDE::*/ function ToBuffer($__dst/*:XByteArray*/)
		{
			$__xv= 0;
			$i=0;
/*{::TO_BUFFER_CODES::}*/
			return $__xv;
		}
		
		public /*::OVER_RIDE::*/ function Size()
		{
			$__xv	= 0;
			$i	=0;
/*{::SIZE_CALC_CODES::}*/
			return $__xv;
		}
   
    public /*::OVER_RIDE::*/ function FromXml(/*XP_XMLNODE_PTR*/ $pNode)
    {
/*{::FROM_XML_CODES::}*/
		  	return $this;
    }
    
    public /*::OVER_RIDE::*/ function   ToXml(/*XSTRING_STREAM & out*/)
    {
        $__xv_out="";
/*{::TO_XML_CODES::}*/
        return $__xv_out;
    }

    public /*::OVER_RIDE::*/  function fromAMFObject($pNode)
    {
        /*{::FROM_AMFOBJECT_CODES::}*/
        return 0;
    }
    
    private static function ParamDebugString($param)
    {
    	if (is_object($param))
    	{
    		return $param->ToDebugString();
    	}
    	else if (is_array($param))
    	{
    		$str = "(";
    		foreach($param as $p)
    		{
    			if( is_object($p) )
    			{
    				$str .= $p->ToDebugString().",";
			}
			else
			{
				$str .= strval($p).",";
			}
    		}
    		$str .= ")";
    		$str = str_replace(",,)",")",$str);
    		return $str;
    	}
    	
    	return strval($param);
    } 
    
	public /*::OVER_RIDE::*/ function ToDebugString()
    {
    	$__xv_out  = "(";
    	
/*{::TO_DEBUG_STRING_CODES::}*/
    	
    	$__xv_out  .= ")";
    	
    	$__xv_out = str_replace(",,)",")",$__xv_out);
    	
    	return $__xv_out;
    }
    
    
	}

?>
