/**
	Auto generated by xproto.exe
@author
	Dany
*/
package /*::PACKAGE_NAME::*/
{
	public final class /*::ENUM_CLASS_NAME::*/
	{
/*::ENUM_CLASS_FIELDS::*/

		public static var  s_szEnumNames:Array = new Array(
/*::ENUM_NAMES_ENTRY::*/);

		public static function getName(_lpValue:int):String
		{
			switch(_lpValue){
/*::ENUM_NAME_CASE_ENTRY::*/
			};
			return "";
		}
	}
}