/**
	Auto generated by xproto.exe
@author
	Dany
*/

package /*::PACKAGE_NAME::*/
{
	public class OpcodeHandler
	{		
		public var szOpcode:String;
		public var handler:Function;
		public function OpcodeHandler(_szOpcode:String,_handler:Function)
		{
			szOpcode = _szOpcode;
			handler = _handler;
		}
	}
}