<?php
/**
	Auto generated by xproto.exe
@author
	Dany
*/
require_once("XByteArray.php");


	class XPACKET_SendInternalNotifyByProxy
	{
		    public static  $_m_xcmd/*:int*/=_EMSG_ServerInterface::CMSG_SendInternalNotifyByProxy;

	    
		public $action/*:INT*/;

	    
	    public function XPACKET_SendInternalNotifyByProxy()
		{
	        $this->action =0;/*INT*/

		}
			
		public static function _Size($action/*:INT*/ )
		{
			$__xv	= 0;
			$i		=0;

            $__xv +=4;//LENGHT
            $__xv +=4;//_m_xcmd
            $__xv +=4;//action

			return $__xv;
		}
				
		public static function _ToBuffer($__dst/*XByteArray*/,$action/*:INT*/ )
		{
			$__xv	= 0;
			$i		=0;

			$__dst->writeInt32(XPACKET_SendInternalNotifyByProxy::_Size($action/*:INT*/ ));
			$__xv +=4;
			$__dst->writeInt32(XPACKET_SendInternalNotifyByProxy::$_m_xcmd);
			$__xv +=4;

            //Write codes of action
            //
            $__dst->writeInt32($action);
            $__xv +=4;

			return $__xv;
		}
		
		public static function _ClassFromParameters($action/*:INT*/ )
		{
			$_class = new XPACKET_SendInternalNotifyByProxy();

            $_class->action=$action;
			
			return $_class;
		}


		public function FromBuffer($__src/*:XByteArray*/)
		{
			$__xv					= 0;
			$i						=0;
			$__xvBeanSize	=0;


            //Read codes of __xvtemp1
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp1=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of __xvtemp2
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp2=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of action
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->action=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

			return $__xv;
		}
		
		public function ToBuffer($__dst/*XByteArray*/)
		{
			return XPACKET_SendInternalNotifyByProxy::_ToBuffer($__dst,$this->action );
		}
		
		public function Size()
		{
			return XPACKET_SendInternalNotifyByProxy::_Size($this->action );
		}

    public  function FromXml(/*XP_XMLNODE_PTR*/ $pNode)
    {

        $this->action = XFROM_XML($this->action,$pNode,"action",0,"");

		  	return 0;
    }
    
    public  function   ToXml(/*XSTRING_STREAM & out*/)
    {
        $__xv_out="";

        $__xv_out .= XTO_XML($this->action,"action",0, 0);

        return $__xv_out;
    }
    
    public   function fromAMFObject($pNode)
    {
       
        
        $this->action = XFROM_AMFOBJECT($this->action,$pNode,"action",0,"");

        return 0;
    }
		
	private static function ParamDebugString($param)
    {
    	if (is_object($param))
    	{
    		return $param->ToDebugString();
    	}
    	else if (is_array($param))
    	{
    		$str = "(";
    		foreach($param as $p)
    		{
    			if( is_object($p) )
    			{
    				$str .= $p->ToDebugString().",";
			}
			else
			{
				$str .= strval($p).",";
			}
    		}
    		$str .= ")";
    		$str = str_replace(",)",")",$str);
    		return $str;
    	}
    	
    	return strval($param);
    } 
    
	public  function ToDebugString()
    {
    	$__xv_out  = "(";
    	
        $__xv_out .= "action=".$this->ParamDebugString($this->action).",";

    	
    	$__xv_out  .= ")";
    	
    	$__xv_out = str_replace(",)",")",$__xv_out);
    	
    	return $__xv_out;
    }
    
   	public static function toAMFObject($__dst/*XByteArray*/,$action/*:INT*/ )
		{
			$__xv	= 0;
			$i		=0;
      $obj = array();

        $obj["action"]=$action ;

      if(count($obj)>0)
      {
          $outBuffer  = WriteAMF3Object($obj);
          $__xv = strlen($outBuffer);
          $__xv+=8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_SendInternalNotifyByProxy::$_m_xcmd);
          $__dst->writeBinary($outBuffer,strlen($outBuffer));
      }
      else
      {
          $__xv =8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_SendInternalNotifyByProxy::$_m_xcmd);
      }
      
      
			return $__xv;
		}
	}
	
	
?>
