<?php
/**
	Auto generated by xproto.exe
@author
	Dany
*/
require_once("XByteArray.php");
/*::PARENT_CLASS_NAME_INCLUDE::*/

	class XPACKET_OnAddCoin
	{
		    public static  $_m_xcmd/*:int*/=_EMSG_ServerEvent::SMSG_OnAddCoin;

	    
		public $item/*:ItemObject*/;

	    
	    public function XPACKET_OnAddCoin()
		{
	        $this->item =new ItemObject();

		}
			
		public static function _Size($item/*:ItemObject*/ )
		{
			$__xv	= 0;
			$i		=0;

            $__xv +=4;//LENGHT
            $__xv +=4;//_m_xcmd
            $__xv +=$item->Size();

			return $__xv;
		}
				
		public static function _ToBuffer($__dst/*XByteArray*/,$item/*:ItemObject*/ )
		{
			$__xv	= 0;
			$i		=0;

			$__dst->writeInt32(XPACKET_OnAddCoin::_Size($item/*:ItemObject*/ ));
			$__xv +=4;
			$__dst->writeInt32(XPACKET_OnAddCoin::$_m_xcmd);
			$__xv +=4;
            $__xv +=$item->ToBuffer($__dst);

			return $__xv;
		}
		
		public static function _ClassFromParameters($item/*:ItemObject*/ )
		{
			$_class = new XPACKET_OnAddCoin();

            $_class->item=$item;
			
			return $_class;
		}


		public function FromBuffer($__src/*:XByteArray*/)
		{
			$__xv					= 0;
			$i						=0;
			$__xvBeanSize	=0;


            //Read codes of __xvtemp1
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp1=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of __xvtemp2
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp2=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }
            $__xv +=$this->item->FromBuffer($__src);

			return $__xv;
		}
		
		public function ToBuffer($__dst/*XByteArray*/)
		{
			return XPACKET_OnAddCoin::_ToBuffer($__dst,$this->item );
		}
		
		public function Size()
		{
			return XPACKET_OnAddCoin::_Size($this->item );
		}

    public  function FromXml(/*XP_XMLNODE_PTR*/ $pNode)
    {

        $this->item = XFROM_XML($this->item,$pNode,"item",3,"");

		  	return 0;
    }
    
    public  function   ToXml(/*XSTRING_STREAM & out*/)
    {
        $__xv_out="";

        $__xv_out .= XTO_XML($this->item,"item",3, 0);

        return $__xv_out;
    }
    
    public   function fromAMFObject($pNode)
    {
       
        
        $this->item = XFROM_AMFOBJECT($this->item,$pNode,"item",3,"");

        return 0;
    }
		
	private static function ParamDebugString($param)
    {
    	if (is_object($param))
    	{
    		return $param->ToDebugString();
    	}
    	else if (is_array($param))
    	{
    		$str = "(";
    		foreach($param as $p)
    		{
    			if( is_object($p) )
    			{
    				$str .= $p->ToDebugString().",";
			}
			else
			{
				$str .= strval($p).",";
			}
    		}
    		$str .= ")";
    		$str = str_replace(",)",")",$str);
    		return $str;
    	}
    	
    	return strval($param);
    } 
    
	public  function ToDebugString()
    {
    	$__xv_out  = "(";
    	
        $__xv_out .= "item=".$this->ParamDebugString($this->item).",";

    	
    	$__xv_out  .= ")";
    	
    	$__xv_out = str_replace(",)",")",$__xv_out);
    	
    	return $__xv_out;
    }
    
   	public static function toAMFObject($__dst/*XByteArray*/,$item/*:ItemObject*/ )
		{
			$__xv	= 0;
			$i		=0;
      $obj = array();

        $obj["item"]=$item ;

      if(count($obj)>0)
      {
          $outBuffer  = WriteAMF3Object($obj);
          $__xv = strlen($outBuffer);
          $__xv+=8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_OnAddCoin::$_m_xcmd);
          $__dst->writeBinary($outBuffer,strlen($outBuffer));
      }
      else
      {
          $__xv =8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_OnAddCoin::$_m_xcmd);
      }
      
      
			return $__xv;
		}
	}
	
	
?>
