<?php
/**
	Auto generated by xproto.exe
@author
	Dany
*/
require_once("XByteArray.php");
/*::PARENT_CLASS_NAME_INCLUDE::*/

	class XPACKET_SendGetCoin
	{
		    public static  $_m_xcmd/*:int*/=_EMSG_ServerInterface::CMSG_SendGetCoin;

	    
		public $itemId/*:string utf-8*/="";

	    
	    public function XPACKET_SendGetCoin()
		{
	
		}
			
		public static function _Size($itemId/*:string utf-8*/ )
		{
			$__xv	= 0;
			$i		=0;

            $__xv +=4;//LENGHT
            $__xv +=4;//_m_xcmd
            $__xv +=XByteArray::StringASize($itemId);

			return $__xv;
		}
				
		public static function _ToBuffer($__dst/*XByteArray*/,$itemId/*:string utf-8*/ )
		{
			$__xv	= 0;
			$i		=0;

			$__dst->writeInt32(XPACKET_SendGetCoin::_Size($itemId/*:string utf-8*/ ));
			$__xv +=4;
			$__dst->writeInt32(XPACKET_SendGetCoin::$_m_xcmd);
			$__xv +=4;

            //Write codes of itemId
            //
             $__xv += XByteArray::WriteStringA($__dst, $itemId);

			return $__xv;
		}
		
		public static function _ClassFromParameters($itemId/*:string utf-8*/ )
		{
			$_class = new XPACKET_SendGetCoin();

            $_class->itemId=$itemId;
			
			return $_class;
		}


		public function FromBuffer($__src/*:XByteArray*/)
		{
			$__xv					= 0;
			$i						=0;
			$__xvBeanSize	=0;


            //Read codes of __xvtemp1
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp1=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of __xvtemp2
            //
            if($__src->getBytesAvailable()>=4)
            {
                $this->__xvtemp2=$__src->readInt32();
                $__xv +=4;
            }
            else
            {
                return 0;
            }

            //Read codes of itemId
            //
            $__itemId_szSize	= new XInteger();
            $this->itemId =XByteArray::ReadStringA($__src,$__itemId_szSize);
            if($__itemId_szSize->_value<=0) 
                return 0;
            $__xv +=$__itemId_szSize->_value;

			return $__xv;
		}
		
		public function ToBuffer($__dst/*XByteArray*/)
		{
			return XPACKET_SendGetCoin::_ToBuffer($__dst,$this->itemId );
		}
		
		public function Size()
		{
			return XPACKET_SendGetCoin::_Size($this->itemId );
		}

    public  function FromXml(/*XP_XMLNODE_PTR*/ $pNode)
    {

        $this->itemId = XFROM_XML($this->itemId,$pNode,"itemId",2,"");

		  	return 0;
    }
    
    public  function   ToXml(/*XSTRING_STREAM & out*/)
    {
        $__xv_out="";

        $__xv_out .= XTO_XML($this->itemId,"itemId",2, 0);

        return $__xv_out;
    }
    
    public   function fromAMFObject($pNode)
    {
       
        
        $this->itemId = XFROM_AMFOBJECT($this->itemId,$pNode,"itemId",2,"");

        return 0;
    }
		
	private static function ParamDebugString($param)
    {
    	if (is_object($param))
    	{
    		return $param->ToDebugString();
    	}
    	else if (is_array($param))
    	{
    		$str = "(";
    		foreach($param as $p)
    		{
    			if( is_object($p) )
    			{
    				$str .= $p->ToDebugString().",";
			}
			else
			{
				$str .= strval($p).",";
			}
    		}
    		$str .= ")";
    		$str = str_replace(",)",")",$str);
    		return $str;
    	}
    	
    	return strval($param);
    } 
    
	public  function ToDebugString()
    {
    	$__xv_out  = "(";
    	
        $__xv_out .= "itemId=".$this->ParamDebugString($this->itemId).",";

    	
    	$__xv_out  .= ")";
    	
    	$__xv_out = str_replace(",)",")",$__xv_out);
    	
    	return $__xv_out;
    }
    
   	public static function toAMFObject($__dst/*XByteArray*/,$itemId/*:string utf-8*/ )
		{
			$__xv	= 0;
			$i		=0;
      $obj = array();

        $obj["itemId"]=$itemId ;

      if(count($obj)>0)
      {
          $outBuffer  = WriteAMF3Object($obj);
          $__xv = strlen($outBuffer);
          $__xv+=8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_SendGetCoin::$_m_xcmd);
          $__dst->writeBinary($outBuffer,strlen($outBuffer));
      }
      else
      {
          $__xv =8;
          $__dst->writeInt32($__xv);
          $__dst->writeInt32(XPACKET_SendGetCoin::$_m_xcmd);
      }
      
      
			return $__xv;
		}
	}
	
	
?>
