/**
	Auto generated by xproto.exe
@author
	Dany
*/

package /*::PACKAGE_NAME::*/
{
	import flash.utils.ByteArray;
	
	public interface IXProtoBeanBase
	{
		function FromBuffer(__src:ByteArray):int;
		function ToBuffer(__dst:ByteArray):int;
		function Size():int;		
	}
}