/**
	Auto generated by xproto.exe
@author
	Dany
*/

package  /*::PACKAGE_NAME::*/
{
	import flash.utils.ByteArray;

	public class /*::BEAN_CLASS_NAME::*/ /*::PARENT_CLASS_NAME::*/
	{
		/*{::PACKET_COMMAND_DEFINES::}*/
	    /*{::CLASS_MEMBER_DEFINES::}*/
	    
		public function /*::BEAN_CLASS_NAME::*/()
		{
			var i:uint=0;
/**::SMART_POINTER_CONSTRUCT::**/
		}
		
		public /*::OVER_RIDE::*/ function FromBuffer(__src:ByteArray):int
		{
			var __xv:int  = 0;
			var i:int=0;
			var __xvBeanSize:int=0;
/*{::FROM_BUFFER_CODES::}*/
			return __xv;
		}
		
		public /*::OVER_RIDE::*/ function ToBuffer(__dst:ByteArray):int
		{
			var __xv:int  = 0;
			var i:int=0;
/*{::TO_BUFFER_CODES::}*/
			return __xv;
		}
		
		public /*::OVER_RIDE::*/ function Size():int
		{
			var __xv:int  = 0;
			var i:int=0;
/*{::SIZE_CALC_CODES::}*/
			return __xv;
		}

		public /*::OVER_RIDE::*/  function fromAMFObject(obj:Object):int
		{
			var i:int=0;
			/*{::FROM_AMFOBJECT_CODES::}*/
			return 0;
		}
		
		private function getSimpleArrayDebugString(value:Array):String
		{
			var i:int=0;
			var __xv_out:String = "(";
			
			if(value != null){
				for(i=0; i <value.length; i++){
					__xv_out += String(value[i])+",";
				} 
			}			
			__xv_out += ")";	
			
			return __xv_out;
		}
		
		private function getObjectArrayDebugString(value:Array):String
		{
			var i:int=0;
			var __xv_out:String = "(";
			
			if(value != null){
				for(i=0; i <value.length; i++){
					__xv_out += value[i].ToDebugString()+",";
				} 
			}
			
			__xv_out += ")";	
			
			return __xv_out;
		}
		
		public /*::OVER_RIDE::*/ function ToDebugString():String
		{
		    var __xv_out:String  = "(";
		    
/*{::TO_DEBUG_STRING_CODES::}*/		    
		    
		    __xv_out += ")";	
    	  return __xv_out.replace(",,)",")");    
		}


		
	}
}