/**
	Auto generated by xproto.exe
@author
	Dany
*/

package  /*::PACKAGE_NAME::*/
{
	import flash.events.Event;
	import flash.utils.ByteArray;

	public class /*::BEAN_CLASS_NAME::*/ extends Event
	{
		/*{::PACKET_COMMAND_DEFINES::}*/
	    /*{::CLASS_MEMBER_DEFINES::}*/
	    
		public function /*::BEAN_CLASS_NAME::*/()
		{
			var i:uint =0;
			super(/*::EVENT_MSG_NAME::*/);
			/**::SMART_POINTER_CONSTRUCT::**/
		}
		
		public static function Clone(src:/*::BEAN_CLASS_NAME::*/, dst:/*::BEAN_CLASS_NAME::*/):int
		{
			var __dst:ByteArray = new ByteArray();
			var ret:int=src.ToBuffer(__dst);
			if(ret>0)
			{
				ret=dst.FromBuffer(__dst);
			}
			return ret;
		}
		
		public static function _Size(/*{::REF_PARAMETERS::}*/):int
		{
			var __xv:int  = 0;
			var i:int=0;
/*{::SIZE_CALC_CODES::}*/
			return __xv;
		}
				
		public static function _ToBuffer(__dst:ByteArray,/*{::REF_PARAMETERS::}*/):int
		{
			var __xv:int  = 0;
			var i:int=0;
/*{::TO_BUFFER_CODES::}*/
			return __xv;
		}


		public function FromBuffer(__src:ByteArray):int
		{
			var __xv:int  = 0;
			var i:int=0;
			var __xvBeanSize:int=0;
/*{::FROM_BUFFER_CODES::}*/
			return __xv;
		}
		
		public function ToBuffer(__dst:ByteArray):int
		{
			return _ToBuffer(__dst,/*{::PASS_PARAMETERS::}*/);
		}
		
		public function Size():int
		{
			return _Size(/*{::PASS_PARAMETERS::}*/);
		}

		public /*::OVER_RIDE::*/  function fromAMFObject(obj:Object):int
		{
			var __xv:int  = 0;
			var i:int=0;
			/*{::FROM_AMFOBJECT_CODES::}*/
			return 0;
		}

		public static function toAMFObject(__dst:ByteArray,/*{::REF_PARAMETERS::}*/):int
		{
			var __xv:int  = 0;
			var i:int=0;
			var obj:Object = new Object();
			var objbytes:ByteArray =  new ByteArray();

/*{::TO_AMFOBJECT_CODES::}*/
			
			__dst.writeInt(8+objbytes.length);
			__dst.writeInt(_m_xcmd);
			if(objbytes.length>0)
				__dst.writeBytes(objbytes,0,objbytes.length);
			__xv = __dst.length;
			return __xv;
		}
		
		public static function _ClassFromParameters(/*{::REF_PARAMETERS::}*/):/*::BEAN_CLASS_NAME::*/
		{
			var _class:/*::BEAN_CLASS_NAME::*/ = new /*::BEAN_CLASS_NAME::*/();
/*{::CLASS_FROM_PARAMETERS_CODES::}*/					
			return _class;
		}
		
		private function getSimpleArrayDebugString(value:Array):String
		{
			var i:int=0;
			var __xv_out:String = "(";
			
			if(value != null){
				for(i=0; i <value.length; i++){
					__xv_out += String(value[i])+",";
				} 
			}			
			__xv_out += ")";	
			
			return __xv_out;
		}
		
		private function getObjectArrayDebugString(value:Array):String
		{
			var i:int=0;
			var __xv_out:String = "(";
			
			if(value != null){
				for(i=0; i <value.length; i++){
					__xv_out += value[i].ToDebugString()+",";
				} 
			}
			
			__xv_out += ")";	
			
			return __xv_out;
		}
				
		public function ToDebugString():String
		{
			if(_m_xcmd == _EMSG_ServerEvent.SMSG_OnSendZipData){
				return "([ignore zip data])";
			}
			
		    var __xv_out:String  = "(";
		    
/*{::TO_DEBUG_STRING_CODES::}*/		    
		    
		    __xv_out  += ")";	
    	  return __xv_out.replace(",,)",")");   
		}
	}
}