/**
	Auto generated by xproto.exe
@author
	Dany
*/

package /*::PACKAGE_NAME::*/
{
	import flash.utils.ByteArray;
	
	public interface /*::LISTENER_INTERFACE_NAME::*/
	{
		function WriteDataToSocket(data:ByteArray):int;
/*::LISTENER_INTERFACE_METHODS::*/
	}
}