/**
	Auto generated by xproto.exe
*/

package componentsx
{
	import flash.utils.ByteArray;

	public class STRINGW implements IXProtoBeanBase
	{
		public function STRINGW()
		{
		}

		public function FromBuffer(__src:ByteArray):int
		{
			return 0;
		}
		
		public function ToBuffer(__dst:ByteArray):int
		{
			return 0;
		}
		
		public function Size():int
		{
			return 0;
		}
		
	}
}