/**
	Auto generated by xproto.exe
@author
	Dany
*/
package /*::PACKAGE_NAME::*/
{
	import flash.utils.ByteArray;

	public class XLONGLONG 
	{
		public var _m_int64Low:uint = 0;
		public var _m_int64High:uint = 0;
		
		public function XLONGLONG()
		{
			
		}

		public function FromBuffer(__src:ByteArray):int
		{
			if(__src.bytesAvailable>=4)
				_m_int64Low =__src.readUnsignedInt();
			else
				return 0;
				
			if(__src.bytesAvailable>=4)
				_m_int64High =__src.readUnsignedInt();
			else
				return 0;
				
			return 8;
		}
		
		public function ToBuffer(__dst:ByteArray):int
		{
			__dst.writeUnsignedInt(_m_int64Low);
			__dst.writeUnsignedInt(_m_int64High);
			
			return 8;
		}
		
		public function Size():int
		{
			return 8;
		}
		
		public function Equal(other:XLONGLONG):Boolean
		{
			if(_m_int64Low == other._m_int64Low && _m_int64High == other._m_int64High)
			{
				return true;
			}
			return false;
		}
		
		/**
		 * @return 
		 * 0  equal
		 * -1 less
		 * 1  greater
		 * */
		public function Compare(other:XLONGLONG):int
		{
			if(_m_int64High > other._m_int64High)
			{
				return 1;
			}
			else if(_m_int64High < other._m_int64High)
			{
				return -1;
			}
			else
			{
				if(_m_int64Low >other._m_int64Low)
				{
					return 1;
				}
				else if(_m_int64Low <other._m_int64Low)
				{
					return -1;
				}
			}
			
			return 0;
		}
	}
}